import { PostCard, Categories } from "../components";
import { getPosts } from "../services";
import NavBar from "../components/NavBar";
import Head from "next/head";

export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Sanatan Astrology</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="Keywords"
          content=" Vedic Astrology Services in English, Czech and Spanish Languages"
        />
        <link rel="icon" href="/img/logosvg.svg" />
      </Head>
      <NavBar />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}

// Fetch data at build time
export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}
